FROM openeuler-22.03-lts-sp2:latest

WORKDIR /root
RUN yum install -y git make gcc cmake python3-pip ruby ruby-devel rubygems-devel npm maven automake perl wget curl
RUN pip install shyaml
CMD ["bash"]